name=BitArray
version=1.0.0
author=Eric VINSONNAUD <eric.vinsonnaud@gmail.com>
maintainer=Eric VINSONNAUD <eric.vinsonnaud@gmail.com>
sentence=A simple library for managing bit array.
paragraph=This library allows you to easily manage bit array .
category=Data Processing
url=https://github.com/ricodev38/BitArray
architectures=*
includes=BitArray.h
